<div class="container center">

    <div class="js-map-loading-icon preloader-wrapper big active" style="display: none">
        <div class="spinner-layer spinner-blue-only">
            <div class="circle-clipper left">
                <div class="circle"></div>
            </div>
            <div class="gap-patch">
                <div class="circle"></div>
            </div>
            <div class="circle-clipper right">
                <div class="circle"></div>
            </div>
        </div>
    </div>
    <div class="js-map">
    </div>

    <div class="menue">
        <form onsubmit="return formSubmit(event);">
            <div class="row">
                <div class="input-field col s12">
                    <input id="nameInput" type="text" required aria-required="true">
                    <label for="nameInput" data-error="Input can't be empty" data-success="perfect">your name</label>
                </div>
            </div>
            <button type="submit" class="btn">Spiel starten</button>
        </form>
    </div>
</div>
