<div class="container center">

    <div class="js-map-loading-icon preloader-wrapper big active">
        <div class="spinner-layer spinner-blue-only">
            <div class="circle-clipper left">
                <div class="circle"></div>
            </div>
            <div class="gap-patch">
                <div class="circle"></div>
            </div>
            <div class="circle-clipper right">
                <div class="circle"></div>
            </div>
        </div>
    </div>
    <div class="js-map">
    </div>

    <div class="menue">
        <div class="input-field col s6">
            <input placeholder="Enter your name here" name="name" id="first_name" type="text" class="validate">
        </div>
        <button onclick="game.startGame()">Starten</button>
    </div>
</div>