# Required to run your project under the correct environment.
language: php

addons:
  code_climate:
    repo_token: 6e0832b132335780ef874dc6f2a44602453ed07df36254e4c6d46bcf435ddfbc

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: hhvm
    - php: nightly


# Commands to be run before your environment runs.
install:
  - composer install --dev --no-interaction --prefer-dist
  - phpenv rehash

# Commands you want to run that will verify your build.
script:
  - composer test
  - phpunit --configuration $DB.phpunit.xml

after_success:
  - vendor/bin/test-reporter
# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always

