language: php
addons:
  code_climate:
    repo_token: 6e0832b132335780ef874dc6f2a44602453ed07df36254e4c6d46bcf435ddfbc
env:
  global:
  - secure: lG2NK3cpkPH6J6xFcsVKdd+1fDOVE3Sm1IX9FaxjbVAOYRFF4AxOYZwrFc7o8UsFlJa84wqxm/ot8rSduuEu+X+ePQKYJtG4DwNQUYoqNeJfb8g73V8BgjBn6sgrE4vMv3VkX4Ld1j8MvQzhFZqSa4dmGLhHsgBGdLNqONs9qI+F7oMiGoXA8TVDS7R1g58Cc/NFFzF/E9E68RHRxESVcote1xUhIjiLEabpTWMJh4BDhm8EBAXffufRsF18rwCbJHd1dXRymA62L0wZ1DOmS2DdqgrWvheOYZ98lg56POMyWuucbNPSiyRv0kCtUP/fms4oQp7vICyvf7W/7WpYz8mnL7uBq+6bGUWnHwcK9ij5WCjSDpDYCSS4ScOqVItMRY4juKdAejzOK0cXakY73I9hmq0MLamDjbj1zfktqZZQ0gvmlhoYPThN8siHUs2qEjkR85SiGbnQoHSovumjcUHXePzU+A4MOJzOxCc85e1vEMJ5LS58/GaWORWNSMG5TDfR0S4wevSfPnDNPIWRHAUuWuNXl0nN3CBzEbxCp7OP/dE0jrxLLh/yS7ChjERMYqJFcS3sep0A3Q0ksw0GZ8QbHv2/1Vogfko31d1FG7Wam58FO/dbwnkc5zKm+IuAtXYIGjBsw2ihaZ6RUcDfGHxgFmmHRqv3TiBwkjsnOKg=

branches:
  except:
    - travis-build

matrix:
  allow_failures:
  - php: nightly
  fast_finish: true
  include:
  - php: 7.0
  - php: 7.1
  - php: nightly

install:
- composer install --dev --no-interaction --prefer-dist
- phpenv rehash

script:
- composer test

after_success:
- vendor/bin/test-reporter
- echo "deployment started..."
- zip -q -r "build-$TRAVIS_BRANCH-v$RELEASE_VERSION+$TRAVIS_BUILD_NUMBER.zip" .
- git config user.name "Travis CI"
- git config user.email "travis@travis-ci.org"
- git stash
- git fetch
- git checkout travis-build
- git stash pop
- mkdir builds
- mv "build-$TRAVIS_BRANCH-v$RELEASE_VERSION+$TRAVIS_BUILD_NUMBER.zip" "builds/build-$TRAVIS_BRANCH-v$RELEASE_VERSION+$TRAVIS_BUILD_NUMBER.zip"
- git add .
- git commit -m "[build] automated travis"
- git remote rm
- git remote add origin "https://ChrisB9:$GH_ACCESS@github.com/derRest/derRest.git"
- git push -fqu origin travis-build
- echo "done."

notifications:
  on_success: never
  on_failure: always
