language: php
addons:
  code_climate:
    repo_token: 6e0832b132335780ef874dc6f2a44602453ed07df36254e4c6d46bcf435ddfbc
env:
  global:
  - secure: lG2NK3cpkPH6J6xFcsVKdd+1fDOVE3Sm1IX9FaxjbVAOYRFF4AxOYZwrFc7o8UsFlJa84wqxm/ot8rSduuEu+X+ePQKYJtG4DwNQUYoqNeJfb8g73V8BgjBn6sgrE4vMv3VkX4Ld1j8MvQzhFZqSa4dmGLhHsgBGdLNqONs9qI+F7oMiGoXA8TVDS7R1g58Cc/NFFzF/E9E68RHRxESVcote1xUhIjiLEabpTWMJh4BDhm8EBAXffufRsF18rwCbJHd1dXRymA62L0wZ1DOmS2DdqgrWvheOYZ98lg56POMyWuucbNPSiyRv0kCtUP/fms4oQp7vICyvf7W/7WpYz8mnL7uBq+6bGUWnHwcK9ij5WCjSDpDYCSS4ScOqVItMRY4juKdAejzOK0cXakY73I9hmq0MLamDjbj1zfktqZZQ0gvmlhoYPThN8siHUs2qEjkR85SiGbnQoHSovumjcUHXePzU+A4MOJzOxCc85e1vEMJ5LS58/GaWORWNSMG5TDfR0S4wevSfPnDNPIWRHAUuWuNXl0nN3CBzEbxCp7OP/dE0jrxLLh/yS7ChjERMYqJFcS3sep0A3Q0ksw0GZ8QbHv2/1Vogfko31d1FG7Wam58FO/dbwnkc5zKm+IuAtXYIGjBsw2ihaZ6RUcDfGHxgFmmHRqv3TiBwkjsnOKg=

branches:
  except:
    - travis-build

matrix:
  allow_failures:
  - php: nightly
  fast_finish: true
  include:
  - php: 7.0
#  - php: 7.1
#  - php: nightly

install:
#- composer install --dev --no-interaction --prefer-dist
- phpenv rehash

script:
#- composer test
- git config user.name "Travis-Build"
- git config user.email "privat@jan-jaeger.de"


after_success:
- vendor/bin/test-reporter
- echo "deployment started..."

- git fetch
- git branch -a #Ausgabe der aktuellen branches

- git remote
- git remote rm origin
- git remote add origin "https://JanJJ:$GH_ACCESS@github.com/derRest/derRest.git"
- git branch -a
- git remote
- git remote -v
- git remote show
- git remote show origin
- git remote show JJ-travis-build-test

- git checkout --track origin/JJ-travis-build-test # -b erzeugt neuen Branch / --track vorhandenen zweig auschecken

#TODO alle zip löschen in builds/ die mit Branch xy anfangen
#- mkdir archive_builds
- git archive $TRAVIS_BRANCH --output=build-$TRAVIS_BRANCH-v$RELEASE_VERSION_$TRAVIS_BUILD_NUMBER.zip --prefix=build/

- git status
#- git add archive_builds/build-$TRAVIS_BRANCH-v$RELEASE_VERSION_$TRAVIS_BUILD_NUMBER.zip
- git add build-$TRAVIS_BRANCH-v$RELEASE_VERSION_$TRAVIS_BUILD_NUMBER.zip
- git status

- git commit -m "CREAT build-$TRAVIS_BRANCH-v$RELEASE_VERSION_$TRAVIS_BUILD_NUMBER.zip"

- git push -fqu origin JJ-travis-build-test
- echo "done."

notifications:
  on_success: never
  on_failure: always