#!/bin/bash

echo "Deleting old release"
github-release delete \
    --user derRest \
    --repo derRest \
    --tag travis-build

commitID=$(git rev-parse HEAD)

echo "Moving tag"
git tag --force travis-build $commitID
git push --force --tags

echo "Creating new release"
github-release release \
    --user derRest \
    --repo derRest \
    --tag travis-build \
    --name "travis build" \
    --description "Autogenerated travis build" \
    --pre-release

