<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title>derRest</title>
    <link rel="icon" href="<?php echo $baseUrl;?>/favicon.ico" type="image/x-icon" />
</head>
<body>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<script>
    var xhr = new XMLHttpRequest();
    xhr.open('GET', location.protocol + '//' + location.host + location.pathname + 'api/maze');
    xhr.onload = function () {
        if (xhr.status === 200) {
            document.querySelector('.json').innerText = xhr.responseText;

            var text = "t1";
            for (i = 0; i < 20; i++) {

              text = text + "<br>"+i;
            }


            document.querySelector('.map').innerText = text; //Ausgabe in div:clas:map
        }
        else {
            document.querySelector('.json').innerText = 'Request failed.  Returned status of ' + xhr.status;
        }
    };
    xhr.send();
</script>
<div class="json"></div>
<div class="trennung">--------------------------------------------------------</div>
<div class="map"></div>
</body>
</html>