<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title>derRest</title>
    <link rel="icon" href="<?php echo $baseUrl;?>/favicon.ico" type="image/x-icon" />
</head>
<body>
<script src="node_modules/jquery/dist/jquery.min.js"></script>
<script>
    function loadJson() {
        var url = location.protocol + '//' + location.host + location.pathname + 'api/maze';
        jQuery.get(url, function(response) {
            console.log(response);
        });
    }
    jQuery(document).ready(function() {
        loadJson();
    });
</script>
<div class="json"></div>
<div class="trennung">--------------------------------------------------------</div>
<div class="map"></div>
</body>
</html>