<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title>derRest</title>
    <link rel="icon" href="<?php echo $baseUrl;?>/favicon.ico" type="image/x-icon" />
</head>
<body>
<script src="node_modules/jquery/dist/jquery.min.js"></script>
<script src="html/readMap.js"></script>
<script>
    function loadJson() {
        var url = location.protocol + '//' + location.host + location.pathname + 'api/maze?x=10&y=15';
        jQuery.get(url, function(response) {
            console.log(response);
            maze.loadMap(response);
        });
    }
    jQuery(document).ready(function() {
        loadJson();
    });
</script>
<center>
    <div class="map"></div>

    <div class="menue">
        <form>
            <label for="name">Name:
                <input id="name">
            </label>

            <button type="button" id="start">Starten</button>
        </form>
    </div>

   <!--- document.getElementById("start").onclick = loadJson(); --->

</center>
</body>
</html>